name: Atualizacao Diaria

on:
  schedule:
    - cron: '0 09 * * *' # Roda às 06:00 AM horário de Brasília
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar Dependências Python
        run: |
          pip install -r requirements.txt

      - name: Rodar Robô
        run: python main.py

      - name: Salvar Dados
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add banco_dados_movimentacao.csv
          git commit -m "Update automático de dados" || exit 0
          git push
